### ISSUE TITLE
Special chars in the user password

### ISSUE THREAD

**Issue by IGZmanuelMartinVivaldi** [jonschlinkert/is-git-url#10]
Passwords with special chars like comma ',', semicolon ':'... are't allowed in the regular expression check

And special chars can't be url encoded because the '%' character isn't accepted neither

Thanks

**Comment by jonschlinkert** [comment]
sorry for the late reply. I think the referenced changes should fix the issue. Please feel free to reopen if it doesn't work for you, or let me know if you have any other issues.
