### ISSUE TITLE
ssh user doesn't have to be git@

### ISSUE THREAD

**Issue by kasbah** [jonschlinkert/is-git-url#7]
When using `git@` git is just the ssh user set up to access the git repository. The name could be any valid ssh user name.

**Comment by jonschlinkert** [comment]
> When using git@ git is just the ssh user set up to access the git repository. The name could be any valid ssh user name.

Should we then rename the library as well? Maybe something like `is-any-kind-of-url`?

(jk, I'd consider a pr but honestly, I'm not sure if that would still fit the description of this library)

**Comment by kasbah** [comment]
Not sure why you comment on this old issue now. Happy for this to be closed. For my use-case this was resolved by forking to [git-clone-able](https://github.com/kasbah/git-clone-able). All I wanted was something on the frontend to check if git will be happy with a given URL.
