### ISSUE TITLE
URL doesn't have to end in .git

### ISSUE THREAD

**Issue by kasbah** [jonschlinkert/is-git-url#8]
It seems ending a remote in `.git` is just a convention. I can easily set up a ssh remote which doesn't end in `.git` and you can definitely clone this very repo with `git clone https://github.com/jonschlinkert/is-git-url`.

**Comment by jonschlinkert** [comment]
> I can easily set up a ssh remote which doesn't end in .git

I could easily drop punctuation and emphasis from my sentences and you could still figure out what I mean, but that doesn't make it idiomatic. I guess we have to draw a line somewhere. I'm not sure how we could infer intent of a non-git url. Any suggestions?

**Comment by kasbah** [comment]
For my use, I need to validate remote (actually remote, not a git remote which could be a local folder) git URLs. If I `git clone` accepts it and it's not on my machine I am ok with it. So I am thinking of _strict_ validation here, not specifying conventions. 

In that case valid URLs are a superset of valid http(s) URLs. Happy to fork and call it something like `is-valid-git-remote-url` or something if that doesn't work with your use-case. Thanks for the project either way!

**Comment by jonschlinkert** [comment]
Closing, since I think that technically the URL you're describing would not be a "git" URL, it would just be a URL.
